[package]
name = "clean-certs"
version = "0.1.0"
edition = "2021"
authors = ["hamflx <a@hamflx.cn>"]

[dependencies]
picky = { version = "7.0.0-rc.4", features = ["pkcs7", "ctl_http_fetch"] }
windows = { version = "0.46.0", features = ["Win32_Foundation", "Win32_Security_Cryptography"] }
